package ptt.vn.icaremobileapp.fragmentutils;

public enum Fragmentez {
    HAPPENINGFRAME,
    HAPPENING,
    RESOLVED,
    INSTRUCTION,
    THAM_KHAM,
    SERVICE_ITEM,
    DRUG_ORDER,
    DRUG_ORDER_OUTSIDE,
    DIAGNOSE,
    DASHBOARD,
    INPATIENT,
    RECEIVING,
    RECEIVING_HI,
    RECEIVING_INFO,
    REGISTER,
    REGISTER_INFO,
    REGISTER_RECEIVE,
    REGISTER_SERVICEITEM,
    PATIENT_LIST
}
